### PR TITLE
Rotate logs hourly; keep logs for the same time (91 days)

### PR DESCRIPTION
**Pull request by matyasselmeci**

### CODE REVIEW

**Comment by matyasselmeci** [comment]
I'll make the same change in opensciencegrid/images once this is merged.

**Review by brianhlin — COMMENTED** [review]
Was this just a problem with the dev instance or is it going to bite us in prod, too? If our main interface for accessing syslog pilot logs is going to be files on disk I'm hesitant to add yet more friction to the process

**Comment by matyasselmeci** [comment]
This was a problem in the prod instance. And most utilities don't deal well with 64 GB (when expanded) text files.

**Review by brianhlin — APPROVED** [review]
LGTM then

**Pull request merged**
